defaults:
  - train_diffusion_unet_timm_umi_workspace
  - override /task: pika
  - _self_

name: train_diffusion_unet_timm_pika_480x640

policy:
  obs_encoder:
    _target_: diffusion_policy.model.vision.pika_obs_encoder.PikaObsEncoder
    rgb_model_name: 'vit_base_patch16_clip_224.openai'
    depth_model_name: 'resnet34.a1_in1k'
    pretrained: True
    frozen: False
    image_size: 224
    depth_max: 2.0
    share_rgb_model: False

logging:
  project: umi
  mode: offline
